### ISSUE TITLE
error: unsatisfiable

### ISSUE THREAD

**Issue by JinHo-C** [ibm-bluemix-mobile-services/bluemix-simple-http-client-swift#19]
Hello

I got "unsatisfiable" error like below with Kitura 1.7.x (In Swift 3.1)

> swift build
Fetching https://github.com/ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-swift.git
Fetching https://github.com/ibm-bluemix-mobile-services/bluemix-simple-http-client-swift.git
error: unsatisfiable

This module is using Kitura-Net 1.6.x and it occurs the 'unsatisfiable' error with Kitura 1.7.x.

I got 'unsatisfiable' error with dependencies like below.
`.Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minor: 7),
  .Package(url: "https://github.com/IBM-Swift/HeliumLogger.git", majorVersion: 1, minor: 7),
  .Package(url: "https://github.com/IBM-Swift/Swift-cfenv.git", majorVersion: 4, minor: 0),
  .Package(url: "https://github.com/IBM-Swift/Kitura-CouchDB.git", majorVersion: 1, minor: 7),
  .Package(url: "https://github.com/IBM-Swift/Swift-Kuery-PostgreSQL.git", majorVersion: 0, minor: 10),
  .Package(url: "https://github.com/ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-swift.git", majorVersion: 0, minor: 7)`

There was no error with dependencies like below.
`.Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minor: 7),
  .Package(url: "https://github.com/IBM-Swift/HeliumLogger.git", majorVersion: 1, minor: 7),
  .Package(url: "https://github.com/IBM-Swift/Swift-cfenv.git", majorVersion: 4, minor: 0),
  .Package(url: "https://github.com/IBM-Swift/Kitura-CouchDB.git", majorVersion: 1, minor: 7),
  .Package(url: "https://github.com/IBM-Swift/Swift-Kuery-PostgreSQL.git", majorVersion: 0, minor: 10)`

**Comment by tunniclm** [comment]
We just need https://github.com/ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-swift.git to pick up a new release containing the fix and then hopefully we can move on to Swift 3.1.1. :smile:

**Comment by AnthonyOliveri** [comment]
Version 0.7.0 has been released with the Kitura and Swift updates. I'll make the same updates to BluemixObjectStorage.
