### ISSUE TITLE
Inconsistent dependency on Kitura-net for Swift 0606

### ISSUE THREAD

**Issue by jagreenwood** [ibm-bluemix-mobile-services/bluemix-simple-http-client-swift#4]
Swift version `DEVELOPMENT-SNAPSHOT-2016-06-06-a`

I'm attempting to build a Kitura app to deploy on Bluemix. My app depends on `bluemix-objectstorage-swift-sdk` which depends on this module.

The issue I'm running in to is this module requires minor version `19`, however Kitura requires minor version `20`

This is leading to `error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/Kitura-net.git)`

**Comment by AntonAleksandrov** [comment]
updated to required .22 of kitura-net
